appartoo_app:
    resource: "@AppartooAppBundle/Resources/config/routing.yml"
    prefix:   /user
    
appartoo_app_api:
    resource: Appartoo\AppBundle\Controller\ApiController
    prefix:   /api
    type: rest

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api-doc

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"