api_get_user:
    path:     /user/{id}
    defaults: { _controller: "AppartooAppBundle:Api:getUser" }
    methods:  [GET]
api_get_users:
    path:     /users
    defaults: { _controller: "AppartooAppBundle:Api:getAllUser" }
    methods:  [GET]
api_get_contact:
    path:     /contact/{id}
    defaults: { _controller: "AppartooAppBundle:Api:getContact" }
    methods:  [GET]
api_get_contacts:
    path:     /contacts
    defaults: { _controller: "AppartooAppBundle:Api:getAllContact"}
api_add_contact:
    path:     /contact/add
    defaults: { _controller: "AppartooAppBundle:Api:addContact"}
    methods:  [POST]
api_add_user:
    path:     /user/add
    defaults: { _controller: "AppartooAppBundle:Api:addUser"}
    methods:  [POST]